[tool.poetry]
name = "dz19"
version = "0.1.0"
description = ""
authors = ["Maksim Zenkin <m.a.zenkin@yandex.ru>"]

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"